server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8

spring:
      banner:
        charset: UTF-8
      http:
        encoding:
        charset: UTF-8
        enabled: true
        force: true
      messages:
        encoding: UTF-8
      mvc:
        view:
          suffix: .html
        favicon:
          enabled: true
#        static-path-pattern: /resources/static/**
          #浏览器不缓存
      thymeleaf:
        cache: false
      jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
      datasource:
#         UTC会有时区问题
        url: jdbc:mysql://127.0.0.1:3306/boot?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#        url: jdbc:mysql://106.12.203.227:3306/boot?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: boot
        password: 123456
      application:
        name: SpringBoot Client
      boot:
        admin:
          client:
            url: http://localhost:8111
#      datasource:
#        name: test
#        url: jdbc:mysql://127.0.0.1:3306/boot?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#        username: boot
#        password: 123456
#        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        filters: stat
#        maxActive: 20
#        initialSize: 1
#        maxWait: 60000
#        minIdle: 1
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: select 'x'
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxOpenPreparedStatements: 20
#        ## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
#mybatis:
#          mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
#          type-aliases-package: com.example.demo.mybaties.model  # 注意：对应实体类的路径
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
mybatis:
  config-location:classpath: /mybatis.xml



management:
  endpoints:
    web:
      exposure:
        include: "*"

